# Tensors

In [89]:
import torch
import h5py

## Tensor Basic Operations

In [2]:
a = [1.0, 2.0, 3.0]
a

[1.0, 2.0, 3.0]

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [17]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [19]:
points_storage = points.storage()
points_storage[0]

4.0

In [20]:
points.storage()[1]

1.0

In [21]:
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

In [25]:
points.stride()

(2, 1)

In [26]:
second_point.stride()

(1,)

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [28]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [30]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [31]:
id(points.storage()) == id(points_t.storage())

True

In [32]:
points.stride()

(2, 1)

In [33]:
points_t.stride()

(1, 2)

In [34]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [35]:
transpose_t.shape

torch.Size([5, 4, 3])

In [36]:
some_t.stride()

(20, 5, 1)

In [37]:
transpose_t.stride()

(1, 5, 20)

In [38]:
points.is_contiguous()

True

In [39]:
points_t.is_contiguous()

False

In [40]:
points_5 = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [41]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t_cont.stride()

(3, 1)

In [43]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

## Named Tensors

In [44]:
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

c:\users\rebs\documents\dev\data-science-env\env\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  """Entry point for launching an IPython kernel.


In [45]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [46]:
batch_t = torch.rand(2, 3, 5, 5)

In [47]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [48]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [49]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [50]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [51]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print('img named: ', img_named.shape, img_named.names)
print('batch names: ', batch_named.shape, batch_named.names)

img named:  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch names:  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [52]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [53]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [54]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [ ]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

## Data Types

In [55]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [56]:
short_points.dtype

torch.int16

In [57]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [58]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [59]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [60]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [72]:
some_list = list(range(6))
print(some_list)
some_list[:] # all
some_list[1:4] # 1 (inclusive) - 4 (not inclusive)
some_list[1:] # 1 (inclusive) onward
some_list[:4] # Everything up to 4 (not inclusive)
some_list[:-1] # Everything up to last item (not inclusive)
some_list[1:4:2] # 1 (inclusive) - 4 (not inclusive) - skip 2

[0, 1, 2, 3, 4, 5]


[1, 3]

In [79]:
print(points)
points[1:] # First row onwards
points[1:, :] # First row onwards, all columns
points[1:, 0] # First row onwards, 0 column
points[None] # Creates another dimension?

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Saving Tensors

In [80]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [82]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
torch.save(points, 'points.t')

In [84]:
with open('points.t', 'wb') as f:
    torch.save(points, f)

In [110]:
points = torch.load('points.t')
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [87]:
with open('points.t', 'rb') as f:
    points = torch.load(f)

In [90]:
f = h5py.File('points.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [91]:
f = h5py.File('points.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [93]:
last_points = torch.from_numpy(dset[-2:])
f.close()

## GPU vs CPU

In [108]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [96]:
points_gpu = points.to(device='cuda')

In [103]:
points_gpu = points.to(device='cuda:0')

In [111]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')
points_gpu

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], device='cuda:0')

In [112]:
points_gpu = points_gpu + 4
points_gpu

tensor([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]], device='cuda:0')

In [113]:
points_cpu = points_gpu.to(device='cpu')

In [114]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()